### ISSUE TITLE
cluster compute instances can't be found

### ISSUE THREAD

**Issue by adsummos** [nathanmarz/storm-deploy#35]
When trying to start up a cc2.8xlarge we get the following error. I think it might be related to the jclouds version, but I'm having trouble upgrading it.

java.util.NoSuchElementException: no hardware profiles support images matching params: [biggest=false, fastest=false, imageName=ubuntu/images/hvm/ubuntu-quantal-12.10-amd64-server-20130206, imageDescription=^099720109477/ubuntu/images/hvm/ubuntu-quantal-12.10-amd64-server-20130206$, imageId=null, imagePredicate=null, imageVersion=^20130206$, location=[id=us-east-1, scope=REGION, description=us-east-1, parent=aws-ec2, iso3166Codes=[US-VA], metadata={}], minCores=16.0, minRam=61952, osFamily=ubuntu, osName=null, osDescription=099720109477/ubuntu/images/hvm/ubuntu-quantal-12.10-amd64-server-20130206, osVersion=, osArch=hvm, os64Bit=true, hardwareId=null, hypervisor=null]
    at org.jclouds.compute.domain.internal.TemplateBuilderImpl.throwNoSuchElementExceptionAfterLoggingHardwareIds(TemplateBuilderImpl.java:683)
    at org.jclouds.compute.domain.internal.TemplateBuilderImpl.resolveHardware(TemplateBuilderImpl.java:717)
    at org.jclouds.compute.domain.internal.TemplateBuilderImpl.build(TemplateBuilderImpl.java:634)
    at org.jclouds.ec2.compute.strategy.EC2CreateNodesInGroupThenAddToSet.execute(EC2CreateNodesInGroupThenAddToSet.java:136)
    at org.jclouds.compute.internal.BaseComputeService.createNodesInGroup(BaseComputeService.java:200)
    at org.jclouds.aws.ec2.compute.AWSEC2ComputeService.createNodesInGroup(AWSEC2ComputeService.java:130)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:90)
    at clojure.lang.Reflector.invokeInstanceMethod(Reflector.java:28)
    at org.jclouds.compute2$create_nodes.invoke(compute2.clj:166)
    at pallet.compute.jclouds.JcloudsService.run_nodes(jclouds.clj:477)
    at pallet.core$create_nodes.invoke(core.clj:845)
    at pallet.core$adjust_node_count.invoke(core.clj:912)
    at pallet.core$parallel_adjust_node_counts$p_a_n_c_future__5497$fn__5498.invoke(core.clj:1003)
    at clojure.lang.AFn.call(AFn.java:18)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
    at java.util.concurrent.FutureTask.run(FutureTask.java:138)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
    at java.lang.Thread.run(Thread.java:680)

**Comment by tbatchelli** [comment]
@adsummos I updated the jclouds libraries in `master`. Could you check if this issue is resolved?

**Comment by adsummos** [comment]
yep, it did and we have successfully brought up a cluster using cc2.8xlarge instances. We had already merged those commits into our fork, but I see you also fixed the issue with it not quitting when finished. Thanks!
