### ISSUE TITLE
Security group does not exist

### ISSUE THREAD

**Issue by xpe** [nathanmarz/storm-deploy#39]
This used to work a week or two ago. Now I'm running against 237270c12b6f and get this error way at the end.

My security groups do not end with "#us-east-1" in the UI; they just look like: "jclouds#nimbus-my-cluster"

```
DEBUG provision - Finished converge
ERROR logging - Exception in thread "main"
ERROR logging - org.jclouds.rest.ResourceNotFoundException: The security group 'jclouds#nimbus-my-cluster#us-east-1' does not exist (NO_SOURCE_FILE:1)
ERROR logging - at clojure.lang.Compiler.eval(Compiler.java:5440)
ERROR logging - at clojure.lang.Compiler.eval(Compiler.java:5415)
ERROR logging - at clojure.lang.Compiler.eval(Compiler.java:5391)
ERROR logging - at clojure.core$eval.invoke(core.clj:2382)
ERROR logging - at clojure.main$eval_opt.invoke(main.clj:235)
ERROR logging - at clojure.main$initialize.invoke(main.clj:254)
ERROR logging - at clojure.main$null_opt.invoke(main.clj:279)
ERROR logging - at clojure.main$main.doInvoke(main.clj:354)
ERROR logging - at clojure.lang.RestFn.invoke(RestFn.java:422)
ERROR logging - at clojure.lang.Var.invoke(Var.java:369)
ERROR logging - at clojure.lang.AFn.applyToHelper(AFn.java:165)
ERROR logging - at clojure.lang.Var.applyTo(Var.java:482)
ERROR logging - at clojure.main.main(main.java:37)
ERROR logging - Caused by: org.jclouds.rest.ResourceNotFoundException: The security group 'jclouds#nimbus-my-cluster#us-east-1' does not exist
ERROR logging - at org.jclouds.aws.handlers.ParseAWSErrorFromXmlContent.refineException(ParseAWSErrorFromXmlContent.java:109)
ERROR logging - at org.jclouds.aws.handlers.ParseAWSErrorFromXmlContent.handleError(ParseAWSErrorFromXmlContent.java:92)
ERROR logging - at org.jclouds.http.handlers.DelegatingErrorHandler.handleError(DelegatingErrorHandler.java:69)
ERROR logging - at org.jclouds.http.internal.BaseHttpCommandExecutorService$HttpResponseCallable.shouldContinue(BaseHttpCommandExecutorService.java:197)
```

**Comment by xpe** [comment]
I just verified that the above commit (34b0d2abddb1) solved the problem I was seeing.

**Comment by gworley3** [comment]
I think I left the comment in the wrong place, but this works for me. I've made essentially the same change in the adsummos fork of storm-deploy, but didn't do it cleanly enough for a pull request.

**Comment by roughley** [comment]
This commit works for me also.

**Comment by oubiwann** [comment]
Had this same error; the patch worked for me as well.
